# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

image: gcc

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  # PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # PDM_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pdm"
  OMPI_MCA_mca_base_component_show_load_errors: 0
  OMPI_CC: gcc # Set the Open MPI C compiler to gcc
  OMPI_CXX: g++ # Set the Open MPI C++ compiler to g++

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip
    - .cache/pdm

stages: # List of stages for jobs, and their order of execution
  - setup
  - build
  - test
  - deploy

before_script:
  - "${SHELL} <(curl -L micro.mamba.pm/install.sh)"
  - micromamba config append channels conda-forge
  - micromamba config set channel_priority strict
  - micromamba --version # For debugging
  # - micromamba install -c conda-forge cmake c-compiler compilers cxx-compiler openmpi openmpi-mpicc git -y # See https://github.com/conda-forge/openmpi-feedstock/issues/61#issuecomment-753001160
  - python --version ; pip --version # For debugging
  - pip install pdm
  - pdm --version # For debugging

setup:
  stage: setup
  script:
    - pdm install

test:
  stage: test
  script:
    - pip install ruff tox # you can also use tox
    - pip install --editable ".[test]"
    - tox --listenvs-all # List the available environments for debugging
    - tox -e py # Do not run ruff by now

run:
  stage: build
  script:
    - pip install .
    # run the command here
  artifacts:
    paths:
      - build/*

pages:
  stage: deploy
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs
    - make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  environment: production
