#!/bin/bash
THIS_PATH=`pwd`

export SEDACS_PATH=$HOME/sedacs/src/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$THIS_PATH/qmd-progress/install/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$THIS_PATH/bml/install/lib64
GPMD_PATH=$THIS_PATH/qmg-progress/examples/gpmdk/build/
export GPMD_PATH=$THIS_PATH/qmd-progress/examples/gpmdk/build/
export PYTHONPATH=$PYTHONPATH:$MOD_PATH:$GPMD_PATH:$LD_LIBRARY_PATH:$SEDACS_PATH
export PYTHONWARNINGS="ignore:Unverified HTTPS request"

