void dnnsp2(double *,
            double *,
            double *,
            float  *,
            float  *,
            float  *,
            float  *,
            float  *,
            void   *,
            void   *,
            int,
            int,
            precision_t,
            refine_t,
	    void *,
	    cudaStream_t *);
